# Generated by Django 4.0.3 on 2022-04-25 11:31

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_chapter_chapter_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='road_choice',
        ),
        migrations.RemoveField(
            model_name='road',
            name='title',
        ),
        migrations.AddField(
            model_name='road',
            name='road_text',
            field=models.CharField(default=1, help_text='The option reader is given', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crossroad',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=book.models.make_audio_path),
        ),
    ]
