# Generated by Django 4.0.3 on 2022-04-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_road_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='road',
            old_name='road_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='crossroad',
            name='text',
            field=models.CharField(default=1, help_text='The question reader is given', max_length=256),
            preserve_default=False,
        ),
    ]
