# Generated by Django 4.0.3 on 2022-05-10 17:22

import book.models
import book.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_crossroad_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('book.chapter',),
        ),
        migrations.AddField(
            model_name='chapter',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crossroad',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='default_book.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='audio',
            field=models.FileField(upload_to=book.models.make_audio_path, validators=[book.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='road',
            name='next_chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.chapter'),
            preserve_default=False,
        ),
    ]
